spring:
  datasource:
    # 配置数据库信息
    mysql:
      driver-class-name: com.mysql.jdbc.Driver
      #数据库密码加密(privateKey/publicKey/passwordEncry通过如下方式加密生成)
      #java –cp druid-1.1.8.jar com.alibaba.druid.filter.config.ConfigTools 你的密码
      privateKey: ${MYSQL_PRIVATEKEY:MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEAqhx8VlhXq6OgUQxWiLSGBi3PIGeCG2c7EvBrq+yYqWGYQh13jmTamQttYBr4Jh+4Rke9ydnTaqmYpNbCUF/IxwIDAQABAkEApYWsMnQpclh3kQVZWhGV64M9bIFrJvDumUIY8qP3867tChjIYxwjD9cyvou7ov/tTBgwXH/jA8MCqru8kgnSAQIhAN4d2lsPUZ+aIAtoOB8ehODH94VnZLGcaj+OM65FhLsBAiEAxA+1bAYbwKVxh03YssrymfFzdB8X6d16c5z57jkJa8cCIQCQ/84PCfYQCc6Hg9a3QfYew4vrc67BX8ngiZVlXA6lAQIhAJvobfln5hvMtDnHMsIC1uaJ9ahqrWaAg8Z6FtlUK+SzAiBrmbPbGXStO0ddM2QhRFd0jZREt47d8cn4GkRVZmIuWA==}
      publicKey: ${MYSQL_PUBLICKEY:MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKocfFZYV6ujoFEMVoi0hgYtzyBnghtnOxLwa6vsmKlhmEIdd45k2pkLbWAa+CYfuEZHvcnZ02qpmKTWwlBfyMcCAwEAAQ==}
      passwordEncry: ${MYSQL_PASSWORDENCRY:An4NyUA+96/EY4yy1jU/r8Vc1p+jse4/ig0pMj52Bxn7HLkXG6fUrTvgXpgExyxo/5nX0wdkB/omrsmyoAB2eQ==}
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${spring.datasource.mysql.publicKey};password=${spring.datasource.mysql.passwordEncry};publickey=${spring.datasource.mysql.publicKey}
      url: jdbc:mysql://${HWORK_DB_HOST:123.56.49.202}:${HWORK_DB_PORT:3306}/${HWORK_DB_DATABASE:demo}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
      username: ${USER_NAME:root}
      password: ${spring.datasource.mysql.passwordEncry}
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: zj6897@qq.com  #QQ邮箱
    password: npbktepgqxiobahd #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: zj6897@qq.com #与上面的username保持一致
swagger:
  #是否开启swagger
  enabled: true
  #标题
  title: hql_tool
  version: 1.0
  description: demo
  base-package: com.hql.tool