spring:
  application:
    name: hql-tool
  profiles:
    active: ${SPRING.PROFILES.ACTIVE:dev}
mybatis:
  type-aliases-package: com.hql.tool.model
  mapper-locations: classpath*:mapper/*.xml
server:
  port: ${PORT:8081}




